### ISSUE TITLE
hasmntopt() may make an incorrect decision.

### ISSUE THREAD

**Issue by 0xbadfca11** [wbx-github/uclibc-ng#8]
E.g. mnt->mnt_opts = "rw,relatime,errors=remount-ro", hasmntopt(mnt, MNTOPT_RO) will match "er**ro**rs".

As a practical matter, e2fsck with uClibc determines that a device mounted with read-write is read-only.

**Comment by fallen** [comment]
I understand the issue here, but the implementation seems to match what the man page says:
```
       The hasmntopt() function scans the mnt_opts field (see below) of the  mntent  struc‐
       ture  mnt  for  a substring that matches opt.  See <mntent.h> and mount(8) for valid
       mount options.
```

```
       The hasmntopt() function returns the address of the substring if a  match  is  found
       and NULL otherwise.

```

It is being implemented as:
```C
char *hasmntopt(const struct mntent *mnt, const char *opt)
{
	return strstr(mnt->mnt_opts, opt);
}

```

which seems to match the man page

**Comment by fallen** [comment]
On the other hand, glibc implementation seems straight forward enough and would fix the issue: https://sourceware.org/git/?p=glibc.git;a=blob;f=misc/mntent_r.c;h=0e8f10007ef8872dd87e9bb2a7b6fc75059cde93;hb=HEAD#l303
Since software seems to use this API... I think it might be a good idea to fix it so that it checks for real option and not just substring.
example of sw using this (glib gio): https://github.com/frida/glib/blob/master/gio/gunixmounts.c#L622

**Comment by 0xbadfca11** [comment]
I see that the specifications requirements are loose

**Comment by fallen** [comment]
Patch sent to the list: https://mailman.uclibc-ng.org/pipermail/devel/2020-October/002049.html

**Comment by wbx-github** [comment]
Patch applied. Thx.
